# Generated by Django 4.1.7 on 2023-04-16 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Propiedad_Descripcion', models.CharField(max_length=200)),
                ('Propiedad_Direccion', models.CharField(max_length=200)),
                ('Numero_Habitaciones', models.PositiveIntegerField()),
                ('Propiedad_Costo', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('Fecha_Publicacion', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
