# Generated by Django 4.1.7 on 2023-04-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewHome', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedades',
            name='Fecha_Publicacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
