# Generated by Django 4.1.7 on 2023-04-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewHome', '0003_alter_propiedades_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedades',
            name='Fecha_Publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
