# Generated by Django 4.1.7 on 2023-04-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewHome', '0006_alter_profile_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
