# Generated by Django 4.1.7 on 2023-04-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewHome', '0008_alter_propiedades_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedades',
            name='imagen',
            field=models.ImageField(upload_to='propiedades'),
        ),
    ]
